### ISSUE TITLE
What is the reason for this?Twice the example file was modified and two errors were reported

### ISSUE THREAD

**Issue by linmx1** [maituoy/BayesianOpt4dftu#12]
[1example.py.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7733343/1example.py.txt)
Traceback (most recent call last):
  File "1example.py", line 1, in <module>
    from BayesOpt4dftu.core import *
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/BayesOpt4dftu/core.py", line 24, in <module>
    from vaspvis import Band
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/vaspvis/__init__.py", line 1, in <module>
    from vaspvis.band import Band
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/vaspvis/band.py", line 8, in <module>
    from pyprocar.utilsprocar import UtilsProcar
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyprocar/__init__.py", line 36, in <module>
    import pyvista
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/__init__.py", line 12, in <module>
    from pyvista.plotting import *
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/plotting/__init__.py", line 7, in <module>
    from .helpers import plot, plot_arrows, plot_compare_four, plot_itk
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/plotting/helpers.py", line 7, in <module>
    from pyvista.utilities import is_pyvista_dataset
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/utilities/__init__.py", line 2, in <module>
    from .errors import (GPUInfo, Observer, Report,
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/utilities/errors.py", line 12, in <module>
    from pyvista import _vtk
  File "/Share/home/Q20301253/miniconda3/envs/my_pymatgen/lib/python3.7/site-packages/pyvista/_vtk.py", line 42, in <module>
    from vtkmodules.vtkRenderingVolumeOpenGL2 import (vtkOpenGLGPUVolumeRayCastMapper,
ImportError: dlopen: cannot load any more object with static TLS

[example (2).txt](https://github.com/maituoy/BayesianOpt4dftu/files/7733363/example.2.txt)

Traceback (most recent call last):
  File "example.py", line 70, in <module>
    main()
  File "example.py", line 50, in main
    calculate(command=VASP_RUN_COMMAND, outfilename=OUTFILENAME, method='hse', import_kpath = import_kpath)
NameError: name 'calculate' is not defined

**Comment by linmx1** [comment]
vaspvis                   1.1.6                    pypi_0    pypi
vtk                       9.1.0           egl_py37he8a1893_3    conda-forge
scikit-learn              1.0.1            py37hf9e9bfc_3    conda-forge
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
python                    3.7.12          hf930737_100_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.21.4           py37h31617e3_0    conda-forge
matplotlib-base           3.5.1            py37h1058ff1_0    conda-forge
ase                       3.22.1             pyhd8ed1ab_1    conda-forge
bayesian-optimization     1.1.0                      py_0    conda-forge
bayesopt4dftu             0.1.2                    pypi_0    pypi

**Comment by linmx1** [comment]
vaspvis 1.1.6 pypi_0 pypi
vtk 9.1.0 egl_py37he8a1893_3 conda-forge
scikit-learn 1.0.1 py37hf9e9bfc_3 conda-forge
scipy 1.7.3 py37hf2a6cf1_0 conda-forge
python 3.7.12 hf930737_100_cpython https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy 1.21.4 py37h31617e3_0 conda-forge
matplotlib-base 3.5.1 py37h1058ff1_0 conda-forge
ase 3.22.1 pyhd8ed1ab_1 conda-forge
bayesian-optimization 1.1.0 py_0 conda-forge
bayesopt4dftu 0.1.2 pypi_0 pypi
......

**Comment by linmx1** [comment]
new err
Traceback (most recent call last):
  File "1example.py", line 68, in <module>
    main()
  File "1example.py", line 60, in main
    bayesianOpt = bayesOpt_DFTU(path='./', kappa=k, alpha_1=a1, alpha_2=a2 )
TypeError: __init__() got an unexpected keyword argument 'alpha_1'

**Comment by maituoy** [comment]
Please upgrade the package to the latest version and see if the problem is resolved.
