### ISSUE TITLE
kpath error

### ISSUE THREAD

**Issue by zc994646659** [maituoy/BayesianOpt4dftu#21]
Hello, 
/data/home/js_lili/.conda/envs/bayes/lib/python3.8/site-packages/pymatgen/symmetry/kpath.py:179: UserWarning: The input structure does not match the expected standard primitive! The path can be incorrect. Use at your own risk.
  warn(
Traceback (most recent call last):
  File "example.py", line 83, in <module>
    main()
  File "example.py", line 71, in main
    obj_next = bayesianOpt.bo()
  File "/data/home/js_lili/.conda/envs/bayes/lib/python3.8/site-packages/BayesOpt4dftu/core.py", line 556, in bo
    next_point_to_probe = self.optimizer.suggest(self.utility_function)
  File "/data/home/js_lili/.conda/envs/bayes/lib/python3.8/site-packages/bayes_opt/bayesian_optimization.py", line 131, in suggest
    suggestion = acq_max(
  File "/data/home/js_lili/.conda/envs/bayes/lib/python3.8/site-packages/bayes_opt/util.py", line 65, in acq_max
    if max_acq is None or -res.fun[0] >= max_acq:
TypeError: 'float' object is not subscriptable
~

**Comment by maituoy** [comment]
Hi, I don't think this is a Kpath issue. Instead, it seems to me that the problem is from the acquisition in BO. Could you provide a minimal example that can reproduce this error? Otherwise, it would be hard for me to help.
